var identifyParams=null;var tasks;var clickPoint;var features=[];var numDatabaseCalls=0;var processedDatabaseCalls=0;var folder=[];var identifyGroup;var theEvt;var identifyGroups=[];var identifyLayers={};var groupContent={};var identifyLayerIds=[];var show_elevation=false;var elevation_url=null;var polySymbol,pointSymbol,lineSymbol;require(["esri/tasks/IdentifyParameters","esri/symbols/SimpleLineSymbol","esri/symbols/SimpleFillSymbol","esri/symbols/PictureMarkerSymbol","dojo/_base/Color"],function(IdentifyParameters,SimpleLineSymbol,SimpleFillSymbol,PictureMarkerSymbol,Color){identifyParams=new IdentifyParameters();identifyParams.tolerance=5;identifyParams.returnGeometry=true;identifyParams.layerOption=IdentifyParameters.LAYER_OPTION_ALL;polySymbol=new SimpleFillSymbol(SimpleFillSymbol.STYLE_SOLID,new SimpleLineSymbol(SimpleLineSymbol.STYLE_SOLID,new Color([255,0,0]),1),new Color([125,125,125,0.35]));pointSymbol=new PictureMarkerSymbol("assets/images/i_flag.png",40,40);lineSymbol=new SimpleLineSymbol(SimpleLineSymbol.STYLE_SOLID,new Color([255,0,10]),1);});function readSettingsWidget(){var xmlhttp=createXMLhttpRequest();var settingsFile=app+"/SettingsWidget.xml?v="+ndisVer;xmlhttp.onreadystatechange=function(){if(xmlhttp.readyState==4&&xmlhttp.status==200){try{require(["dojo/dom","dijit/registry","dojo/query","dojo/dom-construct","dojo/on"],function(dom,registry,query,domConstruct,on){var xmlDoc=createXMLdoc(xmlhttp);var myPrj=getCookie("prj");if(myPrj!=="")
settings={"XYProjection":myPrj};else
settings={"XYProjection":xmlDoc.getElementsByTagName("xy_projection")[0].childNodes[0].nodeValue};registry.byId("settings_xy_proj").set("value",settings.XYProjection);registry.byId("help_xy_proj").set("value",settings.XYProjection);use_map_link=xmlDoc.getElementsByTagName("use_map_link")[0]&&xmlDoc.getElementsByTagName("use_map_link")[0].childNodes[0].nodeValue=="true"?1:0;if(use_map_link){document.getElementById("mapLinkBtn").style.display="block";}
use_get_extent=xmlDoc.getElementsByTagName("use_get_extent")&&xmlDoc.getElementsByTagName("use_get_extent")[0].childNodes[0].nodeValue=="true"?1:0;if(use_get_extent)document.getElementById("showExtentBtn").style.display="block";var use_gmus=xmlDoc.getElementsByTagName("use_gmus")[0]&&xmlDoc.getElementsByTagName("use_gmus")[0].childNodes[0].nodeValue=="true"?1:0;if(use_gmus){settings.useGMUs=true;if(!xmlDoc.getElementsByTagName("gmu_url")[0])
alert("Missing tag: gmu_url in "+app+"/SettingsWidget.xml","Data Error");else
settings.elkUrl=xmlDoc.getElementsByTagName("gmu_url")[0].childNodes[0].nodeValue;if(!xmlDoc.getElementsByTagName("gmu_field")[0])
alert("Missing tag: gmu_field in "+app+"/SettingsWidget.xml","Data Error");else
settings.elkField=xmlDoc.getElementsByTagName("gmu_field")[0].childNodes[0].nodeValue;if(!xmlDoc.getElementsByTagName("sheep_gmu_url")[0])
alert("Missing tag: sheep_gmu_url in "+app+"/SettingsWidget.xml","Data Error");else
settings.sheepUrl=xmlDoc.getElementsByTagName("sheep_gmu_url")[0].childNodes[0].nodeValue;if(!xmlDoc.getElementsByTagName("sheep_gmu_field")[0])
alert("Missing tag: sheep_gmu_field in "+app+"/SettingsWidget.xml","Data Error");else
settings.sheepField=xmlDoc.getElementsByTagName("sheep_gmu_field")[0].childNodes[0].nodeValue;if(!xmlDoc.getElementsByTagName("goat_gmu_url")[0])
alert("Missing tag: goat_gmu_url in "+app+"/SettingsWidget.xml","Data Error");else
settings.goatUrl=xmlDoc.getElementsByTagName("goat_gmu_url")[0].childNodes[0].nodeValue;if(!xmlDoc.getElementsByTagName("goat_gmu_field")[0])
alert("Missing tag: goat_gmu_field in "+app+"/SettingsWidget.xml","Data Error");else
settings.goatField=xmlDoc.getElementsByTagName("goat_gmu_field")[0].childNodes[0].nodeValue;if(gmu=="Big Game GMU")
showGMUCombo(settings.elkUrl,settings.elkField);else if(gmu=="Bighorn GMU")
showGMUCombo(settings.sheepUrl,settings.sheepField);else if(gmu=="Goat GMU")
showGMUCombo(settings.goatUrl,settings.goatField);}
else{settings.useGMUs=false;}
var driving_directions=xmlDoc.getElementsByTagName("driving_directions")[0]&&xmlDoc.getElementsByTagName("driving_directions")[0].childNodes[0].nodeValue=="true"?1:0;if(driving_directions){domConstruct.create("a",{"id":"dirLink","class":"action","innerHTML":"Get Directions","href":"javascript:void(0)"},query(".actionList",map.infoWindow.domNode)[0]);on(dom.byId("dirLink"),"click",getDirections);}
on(query(".actionList .zoomTo")[0],"click",zoomToPt);domConstruct.create("div",{"class":"action","id":"identifyPoint","innerHTML":"Loading click point..."},query(".actionList",map.infoWindow.domNode)[0]);if(xmlDoc.getElementsByTagName("elevation")[0]&&xmlDoc.getElementsByTagName("elevation")[0].firstChild.nodeValue)
show_elevation=xmlDoc.getElementsByTagName("elevation")[0].firstChild.nodeValue=="true"?1:0;if(show_elevation&&xmlDoc.getElementsByTagName("elevation_url")[0]){if(xmlDoc.getElementsByTagName("elevation_url")[0].firstChild.nodeValue)
elevation_url=xmlDoc.getElementsByTagName("elevation_url")[0].firstChild.nodeValue;else alert("Missing elevation_url tag in SettingsWidget.xml.","Data Error");}
folder=xmlDoc.getElementsByTagName("folder");for(var f=0;f<folder.length;f++)
{if(f==0)identifyGroup=folder[f].getAttribute("label");identifyGroups.push(folder[f].getAttribute("label"));identifyLayerIds[identifyGroups[f]]=[];var layer=folder[f].getElementsByTagName("layer");identifyLayers[identifyGroups[f]]=new Object();if(folder[f].getElementsByTagName("desc")[0])
identifyLayers[identifyGroups[f]].desc=folder[f].getElementsByTagName("desc")[0].firstChild.nodeValue;var label="missing label";for(var i=0;i<layer.length;i++){if(!layer[i].getAttribute("label"))
alert("Error in "+app+"/SettingsWidget.xml. Missing label in folder: "+identifyGroups[f]+".","Data Error");else
label=layer[i].getAttribute("label");identifyLayers[identifyGroups[f]][label]=new Object();var found=false;if(!layer[i].getElementsByTagName("url")[0]||!layer[i].getElementsByTagName("id")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing url or id in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else{for(var j=0;j<identifyLayerIds[identifyGroups[f]].length;j++){if(identifyLayerIds[identifyGroups[f]][j].url==layer[i].getElementsByTagName("url")[0].childNodes[0].nodeValue&&identifyLayerIds[identifyGroups[f]][j].geometry==layer[i].getElementsByTagName("geometry")[0].childNodes[0].nodeValue.toLowerCase()){identifyLayerIds[identifyGroups[f]][j].ids.push(layer[i].getElementsByTagName("id")[0].childNodes[0].nodeValue);found=true;}}}
if(!found){if(!layer[i].getElementsByTagName("url")[0]||!layer[i].getElementsByTagName("id")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing url or id in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else{identifyLayerIds[identifyGroups[f]].push({url:layer[i].getElementsByTagName("url")[0].childNodes[0].nodeValue,ids:new Array(layer[i].getElementsByTagName("id")[0].childNodes[0].nodeValue),geometry:layer[i].getElementsByTagName("geometry")[0].childNodes[0].nodeValue.toLowerCase(),id_vis_only:folder[f].getAttribute("id_vis_only")&&folder[f].getAttribute("id_vis_only").toLowerCase()=="true"?true:false});}}
if(layer[i].getElementsByTagName("database")[0]){if(!layer[i].getElementsByTagName("url")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing url in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].url=layer[i].getElementsByTagName("url")[0].childNodes[0].nodeValue;if(!layer[i].getElementsByTagName("id")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing id in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].id=layer[i].getElementsByTagName("id")[0].childNodes[0].nodeValue;if(!layer[i].getElementsByTagName("geometry")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing geometry in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].geometry=layer[i].getElementsByTagName("geometry")[0].childNodes[0].nodeValue;if(!layer[i].getElementsByTagName("fields")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing fields in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].fields=layer[i].getElementsByTagName("fields")[0].childNodes[0].nodeValue.split(",");if(!layer[i].getElementsByTagName("displaynames")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing displaynames in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].displaynames=layer[i].getElementsByTagName("displaynames")[0].childNodes[0].nodeValue.split(",");if(layer[i].getElementsByTagName("position")[0])
identifyLayers[identifyGroups[f]][label].position=layer[i].getElementsByTagName("position")[0].childNodes[0].nodeValue;else
identifyLayers[identifyGroups[f]][label].position=0;if(!layer[i].getElementsByTagName("database")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing database in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].database=layer[i].getElementsByTagName("database")[0].childNodes[0].nodeValue;if(!layer[i].getElementsByTagName("filename")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing filename in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].filename=layer[i].getElementsByTagName("filename")[0].childNodes[0].nodeValue;if(layer[i].getElementsByTagName("one2one_fields")[0]&&layer[i].getElementsByTagName("one2one_fields")[0].childNodes.length>0)
identifyLayers[identifyGroups[f]][label].one2one_fields=layer[i].getElementsByTagName("one2one_fields")[0].childNodes[0].nodeValue.split(",");if(layer[i].getElementsByTagName("one2one_display")[0]&&layer[i].getElementsByTagName("one2one_display")[0].childNodes.length>0)
identifyLayers[identifyGroups[f]][label].one2one_display=layer[i].getElementsByTagName("one2one_display")[0].childNodes[0].nodeValue.split(",");if(layer[i].getElementsByTagName("one2many_fields")[0]&&layer[i].getElementsByTagName("one2many_fields")[0].childNodes.length>0)
identifyLayers[identifyGroups[f]][label].one2many_fields=layer[i].getElementsByTagName("one2many_fields")[0].childNodes[0].nodeValue.split(",");}
else{if(!layer[i].getElementsByTagName("url")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing url in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].url=layer[i].getElementsByTagName("url")[0].childNodes[0].nodeValue;if(!layer[i].getElementsByTagName("id")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing id in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].id=layer[i].getElementsByTagName("id")[0].childNodes[0].nodeValue;if(!layer[i].getElementsByTagName("geometry")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing geometry in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].geometry=layer[i].getElementsByTagName("geometry")[0].childNodes[0].nodeValue;if(!layer[i].getElementsByTagName("fields")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing fields in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].fields=layer[i].getElementsByTagName("fields")[0].childNodes[0].nodeValue.split(",");if(!layer[i].getElementsByTagName("displaynames")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing displaynames in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].displaynames=layer[i].getElementsByTagName("displaynames")[0].childNodes[0].nodeValue.split(",");if(label=="Big Game GMU"){identifyLayers[identifyGroups[f]]["Bighorn GMU"]=new Object();identifyLayers[identifyGroups[f]]["Bighorn GMU"].url=settings.sheepUrl.slice(0,settings.sheepUrl.length-2);identifyLayers[identifyGroups[f]]["Bighorn GMU"].id=settings.sheepUrl.slice(settings.sheepUrl.length-1);identifyLayers[identifyGroups[f]]["Bighorn GMU"].geometry="polygon";identifyLayers[identifyGroups[f]]["Bighorn GMU"].fields=[settings.sheepField];identifyLayers[identifyGroups[f]]["Bighorn GMU"].displaynames=["GMU Number"];identifyLayers[identifyGroups[f]]["Goat GMU"]=new Object();identifyLayers[identifyGroups[f]]["Goat GMU"].url=settings.goatUrl.slice(0,settings.goatUrl.length-2);identifyLayers[identifyGroups[f]]["Goat GMU"].id=settings.goatUrl.slice(settings.goatUrl.length-1);identifyLayers[identifyGroups[f]]["Goat GMU"].geometry="polygon";identifyLayers[identifyGroups[f]]["Goat GMU"].fields=[settings.goatField];identifyLayers[identifyGroups[f]]["Goat GMU"].displaynames=["GMU Number"];}}}}
drawInit();});}
catch(e){alert("Error reading "+app+"/SettingsWidget.xml in javascript/identify.js readSettingsWidget(): "+e.message,"Data Error",e);hideLoading("");}}
else if(xmlhttp.status===404){alert("Error: Missing "+app+"/settingsWidget.xml file.","Data Error");hideLoading();}
else if(xmlhttp.readyState===4&&xmlhttp.status===500){alert("Error reading "+app+"/settingsWidget.xml.","Code Error");hideLoading();}};xmlhttp.open("GET",settingsFile,true);xmlhttp.send();}
function doIdentify(evt){if(drawing)return;require(["dojo/dom-construct","dojo/query","dojo/dom","dojo/on","dojo/domReady!"],function(domConstruct,query,dom,on){numDatabaseCalls=0;processedDatabaseCalls=0;features=[];theEvt=evt;showLoading();for(var i=0;i<identifyGroups.length;i++){groupContent[identifyGroups[i]]=null;}
clickPoint=evt.mapPoint;map.infoWindow.hide();map.infoWindow.setTitle("Identify");map.infoWindow.setContent("<p align='center'>Loading...</p>");dom.byId("identifyPoint").innerHTML="Loading click point...";if(elevation_url){if(query(".actionList #elevation",map.infoWindow.domNode)[0]){domConstruct.empty(query(".actionList #elevation",map.infoWindow.domNode)[0]);domConstruct.place(domConstruct.toDom("Elevation: loading..."),query(".actionList #elevation",map.infoWindow.domNode)[0]);}
else{domConstruct.create("span",{"class":"action","id":"elevation","innerHTML":"Elevation: loading..."},query(".actionList",map.infoWindow.domNode)[0]);}}
map.infoWindow.show(clickPoint);displayContent();});}
function displayContent(){var deferreds;require(["esri/tasks/IdentifyParameters","dojo/_base/array","esri/tasks/IdentifyTask","dojo/DeferredList","dojo/_base/Deferred"],function(IdentifyParameters,array,IdentifyTask,DeferredList,Deferred){if(groupContent[identifyGroup]){map.infoWindow.setContent(groupContent[identifyGroup]);hideLoading("");return;}
var task;identifyParams.geometry=clickPoint;identifyParams.mapExtent=map.extent;identifyParams.width=map.width;identifyParams.height=map.height;var deferreds=array.map(identifyLayerIds[identifyGroup],function(item){if(item)
{var vis_layers;task=new IdentifyTask(item.url);identifyParams.layerIds=item.ids.slice();if(item.geometry!="polygon"){if(map.getScale()<=36112)
identifyParams.tolerance=25;else if(map.getScale()<=288895)
identifyParams.tolerance=20;else
identifyParams.tolerance=10;}
else
identifyParams.tolerance=1;if(item.id_vis_only){var layers=map.getLayersVisibleAtScale(map.getScale());var url=item.url;if(item.url[item.url.length-1]=="/")url=item.url.substr(0,item.url.length-1);vis_layers=[];array.forEach(layers,function(layer){if(layer.url==url){if(layer.visible==true){for(var i=0;i<identifyParams.layerIds.length;i++){if(layer.layerInfos[identifyParams.layerIds[i]].parentLayerId==-1||layer.layerInfos[identifyParams.layerIds[i]].visible==false){if(layer.layerInfos[identifyParams.layerIds[i]].visible==true)
vis_layers.push(identifyParams.layerIds[i]);}
else if(layer.layerInfos[layer.layerInfos[identifyParams.layerIds[i]].parentLayerId].parentLayerId==-1||layer.layerInfos[layer.layerInfos[identifyParams.layerIds[i]].parentLayerId].visible==false){if(layer.layerInfos[layer.layerInfos[identifyParams.layerIds[i]].parentLayerId].visible==true)
vis_layers.push(identifyParams.layerIds[i]);}
else if(layer.layerInfos[layer.layerInfos[layer.layerInfos[identifyParams.layerIds[i]].parentLayerId].parentLayerId].parentLayerId==-1||layer.layerInfos[layer.layerInfos[layer.layerInfos[identifyParams.layerIds[i]].parentLayerId].parentLayerId].visible==false){if(layer.layerInfos[layer.layerInfos[layer.layerInfos[identifyParams.layerIds[i]].parentLayerId].parentLayerId].visible==true)
vis_layers.push(identifyParams.layerIds[i]);}}}
identifyParams.layerIds=vis_layers;}});}
else identifyParams.layerOption=IdentifyParameters.LAYER_OPTION_ALL;if(settings.elkUrl&&item.url==settings.elkUrl.slice(0,settings.elkUrl.lastIndexOf("/")+1)&&gmu!="Big Game GMU"){var index=identifyParams.layerIds.indexOf(settings.elkUrl.slice(settings.elkUrl.lastIndexOf("/")+1));if(index>-1)identifyParams.layerIds.splice(index,1);}
return task.execute(identifyParams,identifySuccess,handleQueryError);}});if(identifyGroup=="GMU and Land Management"){if(gmu=="Bighorn GMU"){identifyParams.tolerance=1;identifyParams.layerIds=[settings.sheepUrl.slice(settings.sheepUrl.lastIndexOf("/")+1)];task=new IdentifyTask(settings.sheepUrl.slice(0,settings.sheepUrl.lastIndexOf("/")+1));deferreds.push(task.execute(identifyParams,identifySuccess,handleQueryError));}
else if(gmu=="Goat GMU"){identifyParams.tolerance=1;identifyParams.layerIds=[settings.goatUrl.slice(settings.goatUrl.lastIndexOf("/")+1)];task=new IdentifyTask(settings.goatUrl.slice(0,settings.goatUrl.lastIndexOf("/")+1));deferreds.push(task.execute(identifyParams,identifySuccess,handleQueryError));}}
var dlist=new DeferredList(deferreds);dlist.then(handleQueryResults);});}
function identifySuccess(e){}
function handleQueryError(e){if(e.details)
alert("Error in identify.js/doIdentify.  "+e.details+" "+e.message+" Check "+app+"/SettingsWidget.xml urls.","Data Error");else
alert("Error in identify.js/doIdentify.  "+e.message+" Check "+app+"/SettingsWidget.xml urls.","Data Error");hideLoading("");}
function handleQueryResults(results){require(["dojo/_base/array"],function(array){try{if(!results){alert("Error in identify.js/handleQueryResults. IdentifyTask returned null.","Data Error");return;}
var title,title_subject;array.forEach(results,function(result){if(result[1]&&result[1].length>0){array.forEach(result[1],function(r){if(typeof identifyLayers[identifyGroup][r.layerName]!='undefined')
if(typeof identifyLayers[identifyGroup][r.layerName].database!='undefined')numDatabaseCalls++;});}});index=0;while(XMLHttpRequestObjects.length>0){XMLHttpRequestObjects.pop();}
title="<span style='float:left;width:255px;text-overflow:ellipsis;'>Show: <select id='id_group' name='id_group' style='margin: 5px;color:black;' onChange='changeIdentifyGroup(this)'>";for(var i=0;i<identifyGroups.length;i++){title+="<option";if(identifyGroup==identifyGroups[i])title+=" selected";title+=">"+identifyGroups[i]+"</option>";}
title+="</select></span>";map.infoWindow.setTitle(title);var str=getIdentifyHeader(identifyGroup);var tmpStr;array.forEach(results,function(result){if(result[1].length>0){array.forEach(result[1],function(r){var feature=r.feature;var infoTemplate;feature.attributes.layerName=r.layerName;if(typeof identifyLayers[identifyGroup][r.layerName]!='undefined'){if(typeof identifyLayers[identifyGroup][r.layerName].database!='undefined'){try{createMultiXMLhttpRequest();var url=app+"/"+identifyLayers[identifyGroup][r.layerName].database+"?v="+ndisVer+"&key="+r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[0]];XMLHttpRequestObjects[index].open("GET",url,true);XMLHttpRequestObjects[index].onreadystatechange=function(arrIndex){return function(){if(XMLHttpRequestObjects[arrIndex].readyState==4){if(XMLHttpRequestObjects[arrIndex].status==200){tmpStr=r.layerName+"</strong><div style='padding-left: 10px;'>";var xmlDoc=createXMLdoc(XMLHttpRequestObjects[arrIndex]);for(i=0;i<identifyLayers[identifyGroup][r.layerName].displaynames.length;i++){if((i>0&&r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]&&r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]!==" "&&r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]!=="Null"&&r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]!=="")){if(r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]].substring(0,4)=="http")
tmpStr+="<a href='"+r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]+"' target='_blank'>"+identifyLayers[identifyGroup][r.layerName].displaynames[i]+"</a>";else{if((r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]].substring(0,7)=="<a href")&&(r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]].indexOf("target")==-1))
tmpStr+=identifyLayers[identifyGroup][r.layerName].displaynames[i]+": "+r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]].replace(">"," target='_blank'>");else
tmpStr+=identifyLayers[identifyGroup][r.layerName].displaynames[i]+": "+r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]];}
tmpStr+="<br/>";}
if(identifyLayers[identifyGroup][r.layerName].position==i){if(typeof identifyLayers[identifyGroup][r.layerName].one2one_fields!="undefined"){for(j=0;j<identifyLayers[identifyGroup][r.layerName].one2one_fields.length;j++){if(xmlDoc.getElementsByTagName(identifyLayers[identifyGroup][r.layerName].one2one_fields[j]).length>0){var one2one_field=xmlDoc.getElementsByTagName(identifyLayers[identifyGroup][r.layerName].one2one_fields[j])[0];if((one2one_field.getElementsByTagName("linkname").length>0)&&(one2one_field[h].getElementsByTagName("linkurl").length>0)){tmpStr+=identifyLayers[identifyGroup][r.layerName].one2one_display[j]+": ";tmpStr+="<a href='"+one2one_field.getElementsByTagName("linkurl")[0].firstChild.nodeValue+"'>"+one2one_field.getElementsByTagName("linkname")[0].firstChild.nodeValue+"</a>";tmpStr+="<br/>";}
else if(one2one_field.childNodes.length>0){tmpStr+=identifyLayers[identifyGroup][r.layerName].one2one_display[j]+": ";tmpStr+=one2one_field.childNodes[0].nodeValue;tmpStr+="<br/>";}}}}
if(typeof identifyLayers[identifyGroup][r.layerName].one2many_fields!="undefined"){for(j=0;j<identifyLayers[identifyGroup][r.layerName].one2many_fields.length;j++){var one2many=xmlDoc.getElementsByTagName(identifyLayers[identifyGroup][r.layerName].one2many_fields[j]);tmpStr+=identifyLayers[identifyGroup][r.layerName].displaynames[0]+":<ul style='margin-top: 0px; margin-bottom: 0px;'>";for(var h=0;h<one2many.length;h++){if((one2many[h].getElementsByTagName("linkname").length>0)&&(one2many[h].getElementsByTagName("linkurl").length>0)){tmpStr+="<li><a href='"+one2many[h].getElementsByTagName("linkurl")[0].firstChild.nodeValue+"' target='_blank'>"+one2many[h].getElementsByTagName("linkname")[0].firstChild.nodeValue+"</a></li>";}
else{tmpStr+="<li>"+one2many[h].childNodes[0].nodeValue+"</li>";}}
tmpStr+="</ul style='margin-bottom: 0px; margin-top: 0px;'>";}}}}
tmpStr+="</div><br/>"
processedDatabaseCalls++;if(str.indexOf(tmpStr)==-1){str+="<div><strong>"+tmpStr;groupContent[identifyGroup]=str;map.infoWindow.setContent(str);map.infoWindow.show(clickPoint);}
features.push(r.feature);}
else{if(XMLHttpRequestObjects[arrIndex].status==404){alert("Identify failed. File not found: "+url,"Data Error");processedDatabaseCalls=numDatabaseCalls;displayInfoWindow();}
else{alert("Identify failed for call to "+url+". Make sure it exists and does not have errors. Must be in the same directory as index.html or a lower directory. XMLHttpRequestObjects["+arrIndex+"].status was "+XMLHttpRequestObjects[arrIndex].status,"Data Error");processedDatabaseCalls=numDatabaseCalls;displayInfoWindow();}}
var isAllComplete=true;for(var i=0;i<numDatabaseCalls;i++){if((!XMLHttpRequestObjects[i])||(XMLHttpRequestObjects[i].readyState!==4)){isAllComplete=false;break;}}
if(isAllComplete){displayInfoWindow();}}}}(index);XMLHttpRequestObjects[index].send();}
catch(error){alert("Identify on "+r.layerName+" failed with error: "+error.message+" in javascript/identify.js handleQueryResults().","Data Error");console.log(error.message);hideLoading("");}}
else{tmpStr=r.layerName+"</strong><div style='padding-left: 10px;'>";var first=true;for(i=0;i<identifyLayers[identifyGroup][r.layerName].displaynames.length;i++){if((r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]&&r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]!==" "&&r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]!=="Null"&&r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]!=="")){if(first)first=false;else tmpStr+="<br/>";if(r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]].substring(0,4)=="http")
tmpStr+="<a href='"+r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]+"' target='_blank'>"+identifyLayers[identifyGroup][r.layerName].displaynames[i]+"</a>";else
tmpStr+=identifyLayers[identifyGroup][r.layerName].displaynames[i]+": "+r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]];}}
tmpStr+="</div></div><br/>";if(str.indexOf(tmpStr)==-1){str+="<div><strong>"+tmpStr;groupContent[identifyGroup]=str;map.infoWindow.setContent(str);map.infoWindow.show(clickPoint);}
features.push(r.feature);}}});}});displayInfoWindow();}
catch(e){alert(e.message+" in javascript/identify.js handleQueryResults().","Code Error",e);hideLoading("");}});}
function highlightFeature(id){require(["esri/graphic","esri/layers/GraphicsLayer"],function(Graphic,GraphicsLayer){var highlightSymbol;if(features[id].geometry.type==="polygon"){highlightSymbol=polySymbol;}
else if(features[id].geometry.type==="point"){highlightSymbol=pointSymbol;}
else if(features[id].geometry.type==="line"){highlightSymbol=lineSymbol;}
var identifyGraphicsLayer=newGraphicsLayer();identifyGraphicsLayer.id="identifygraphics";for(var i=0;i<features.length;i++){if(features[i].attributes.layerName==features[id].attributes.layerName)
identifyGraphicsLayer.add(new Graphic(features[id].geometry,highlightSymbol));}
map.addLayer(identifyGraphicsLayer);identifyGraphicsLayer=null;highlightSymbol=null;});}
function removeHighlight(){if(map.getLayer("identifygraphics"))
map.removeLayer(map.getLayer("identifygraphics"));}
function getIdentifyHeader(name){if(identifyLayers[name].desc)return"<div class='esriPopupItemTitle'>"+name+" found at map click:</div><br/><p style='font-style:italic;top:-15px;position:relative;'>"+identifyLayers[name].desc+"</p>";else
return"<div class='esriPopupItemTitle'>"+name+" found at map click:</div><br/>";}
function getIdentifyFooter(){require(["dojo/dom","dijit/registry","esri/geometry/webMercatorUtils","esri/SpatialReference","esri/tasks/ProjectParameters","esri/tasks/GeometryService"],function(dom,registry,webMercatorUtils,SpatialReference,ProjectParameters,GeometryService){try{var geoPt;if(registry.byId("settings_xy_proj").value==="dd"){geoPt=webMercatorUtils.webMercatorToGeographic(clickPoint);dom.byId("identifyPoint").innerHTML="Lat Long: "+geoPt.y.toFixed(5)+" N, "+geoPt.x.toFixed(5)+" W";}
else if(registry.byId("settings_xy_proj").value==="dms"){geoPt=mappoint_to_dms(clickPoint,true);dom.byId("identifyPoint").innerHTML="Lat Long: "+geoPt[0]+" N, "+geoPt[1]+" W";}
else if(registry.byId("settings_xy_proj").value==="dm"){geoPt=mappoint_to_dm(clickPoint,true);dom.byId("identifyPoint").innerHTML="Lat Long: "+geoPt[0]+" N, "+geoPt[1]+" W";}
else{var outSR=new SpatialReference(Number(registry.byId("settings_xy_proj").value));var params=new ProjectParameters();params.geometries=[clickPoint];params.outSR=outSR;geometryService.project(params,function(feature){var units;if(outSR.wkid==32612)units="WGS84 UTM Zone 12N";else if(outSR.wkid==32613)units="WGS84 UTM Zone 13N";else if(outSR.wkid==26912)units="NAD83 UTM Zone 12N";else if(outSR.wkid==26913)units="NAD83 UTM Zone 13N";else if(outSR.wkid==26712)units="NAD27 UTM Zone 12N";else if(outSR.wkid==26713)units="NAD27 UTM Zone 13N";else units="unknown units";dom.byId("identifyPoint").innerHTML=units+": "+feature[0].x.toFixed(0)+", "+feature[0].y.toFixed(0);},function(err){if(err.details)
alert("Problem projecting point. "+err.message+" "+err.details[0],"Warning");else
alert("Problem projecting point. "+err.message,"Warning");hideLoading("");});}}
catch(e){alert(e.message+" in javascript/identify.js getIdentifyFooter().","Code Error",e);}});}
function changeIdentifyGroup(sel){identifyGroup=sel.options[sel.selectedIndex].value;map.infoWindow.setContent("<p align='center'>Loading...</p>");features=[];numDatabaseCalls=0;processedDatabaseCalls=0;displayContent();}
function displayInfoWindow(){if(numDatabaseCalls==processedDatabaseCalls){numDatabaseCalls=0;processedDatabaseCalls=0;getIdentifyFooter();if(features.length==0){var str;var visible="";if(identifyLayerIds[identifyGroup][0].id_vis_only)visible="visible ";if(identifyLayers[identifyGroup].desc){str="<div><p style='font-style:italic;top:-15px;position:relative;'>"+identifyLayers[identifyGroup].desc+"</p>No "+visible+identifyGroup+" at this point.<br/><br/></div>";map.infoWindow.setContent(str);groupContent[identifyGroup]=str;str=null;}
else{str="<div>No "+visible+identifyGroup+" at this point.<br/><br/></div>";map.infoWindow.setContent(str);groupContent[identifyGroup]=str;str=null;}}
if(elevation_url){require(["esri/request"],function(esriRequest){var ext='{"xmin":'+map.extent.xmin+',"ymin":'+map.extent.ymin+',"xmax":'+map.extent.xmax+',"ymax":'+map.extent.ymax+',"spatialReference":{"wkid":102100,"latestWkid":102100}}';var layersRequest=esriRequest({url:elevation_url+"/identify",content:{f:"json",geometry:JSON.stringify(clickPoint),geometryType:"esriGeometryPoint",tolerance:"5",mapExtent:ext,sr:"102100",imageDisplay:map.width+","+map.height+",96",returnGeometry:false},handleAs:"json",callbackParamName:"callback"});layersRequest.then(function(response){require(["dojo/dom-attr","dojo/dom-construct","dojo/query","dojo/dom","dojo/on","dojo/domReady!"],function(domAttr,domConstruct,query,dom,on){if(query(".actionList #elevation",map.infoWindow.domNode)[0]){domConstruct.empty(query(".actionList #elevation",map.infoWindow.domNode)[0]);domConstruct.place(domConstruct.toDom("Elevation: "+Math.round(response.results[0].attributes["Pixel Value"])+" ft "+Math.round(response.results[0].attributes["Pixel Value"]*0.3048)+" m"),query(".actionList #elevation",map.infoWindow.domNode)[0]);}
else{domConstruct.create("span",{"class":"action","id":"elevation","innerHTML":"Elevation: "+Math.round(response.results[0].attributes["Pixel Value"])+" ft "+Math.round(response.results[0].attributes["Pixel Value"]*0.3048)+" m"},query(".actionList",map.infoWindow.domNode)[0]);}});},function(error){require(["dojo/dom-attr","dojo/dom-construct","dojo/query","dojo/dom","dojo/on","dojo/domReady!"],function(domAttr,domConstruct,query,dom,on){if(query(".actionList #elevation",map.infoWindow.domNode)[0]){domConstruct.empty(query(".actionList #elevation",map.infoWindow.domNode)[0]);domConstruct.place(domConstruct.toDom("Elevation: data not available"),query(".actionList #elevation",map.infoWindow.domNode)[0]);}
else{domConstruct.create("span",{"class":"action","id":"elevation","innerHTML":"Elevation: data not available"},query(".actionList",map.infoWindow.domNode)[0]);}});hideLoading("");});});}
map.infoWindow.show(clickPoint);hideLoading("");}}
function getDirections(evt){require(["esri/geometry/webMercatorUtils"],function(webMercatorUtils){var geoPt=webMercatorUtils.webMercatorToGeographic(clickPoint);var url="http://google.com/maps?output=classic&q="+geoPt.y+","+geoPt.x;window.open(url,"_blank");});}
function zoomToPt(){var level=5;if(map.getLevel()>5)level=map.getLevel();map.centerAndZoom(clickPoint,level);}