define(["dojo/_base/declare","dojo/_base/lang"],function(declare,lang){return{mlGetPoints:function(){var url=null;var singleQuote=/'/g;var doubleQuote=/"/g;for(var i=0;i<drawGraphicsCount.length;i++){var layer=map.getLayer(drawGraphicsCount[i]).graphics[0];if(layer.geometry.type!="point")continue;if(!url)url="&point=";if(url!="&point=")url+=",";var rgb=layer.symbol.color.toRgb();var size="m";if(layer.symbol.size==7)size="s";else if(layer.symbol.size==21)size="l";var ptColor="y";if(rgb[0]==255)ptColor="r";else if(rgb[1]==255)ptColor="g";else if(rgb[2]==255)ptColor="b";url+=size+"|"+ptColor+"|"+parseInt(layer.geometry.x)+"|"
+parseInt(layer.geometry.y);var id=1;if(detectmob)id=2;if(map.getLayer(drawGraphicsCount[i]).graphics[id]){if(id==2)layer=map.getLayer(drawGraphicsCount[i]).title;else layer=map.getLayer(drawGraphicsCount[i]).graphics[id].symbol.text;url+="|"+layer.replace(singleQuote,"\%27").replace(doubleQuote,"\%22").replace(/,/g,";").replace(/\n/g,"\%0D").replace(/\?/g,"\%3F");}
else url+="|Way%20Point";if(map.getLayer(drawGraphicsCount[i]).desc){var desc=map.getLayer(drawGraphicsCount[i]).desc;if(desc[desc.length-1]==".")desc+=" ";url+="|"+desc.replace(singleQuote,"\%27").replace(doubleQuote,"\%22").replace(/,/g,";").replace(/\n/g,"\%0D").replace(/\?/g,"\%3F");}}
return url;},mlGetLayers:function(){var str="&layer="+mapBasemap+"|";var layer=map.getLayersVisibleAtScale();for(var i=0;i<layer.length;i++){if(layer[i].declaredClass=="esri.layers.ArcGISDynamicMapServiceLayer"){if(!layer[i].visible)continue;if(str.substring(str.length-1,str.length)!="|"){str+=",";}
var op=layer[i].opacity.toString();str+=layer[i].id+"|"+op.substring(0,4)+"|";for(var k=0;k<layer[i].layerInfos.length;k++){if(layer[i].visibleLayers.indexOf(k)!=-1){var id=k;while(layer[i].layerInfos[id].parentLayerId!=-1){if(layer[i].visibleLayers.indexOf(layer[i].layerInfos[id].parentLayerId)==-1)
layer[i].visibleLayers.push(layer[i].layerInfos[id].parentLayerId);id=layer[i].layerInfos[id].parentLayerId;}
layer[i].visibleLayers=layer[i].visibleLayers.sort(function(a,b){return a-b})}}
for(var j=0;j<layer[i].visibleLayers.length;j++){if(j!=0)str+="-";str+=layer[i].visibleLayers[j];}}}
return str;},addPoints:function(points,sr){require(["esri/graphic","esri/layers/GraphicsLayer","esri/geometry/Point","esri/symbols/SimpleMarkerSymbol","esri/symbols/SimpleLineSymbol","dojo/_base/Color","esri/geometry/Geometry","esri/SpatialReference"],function(Graphic,GraphicsLayer,Point,SimpleMarkerSymbol,SimpleLineSymbol,Color,Geometry,SpatialReference){var pointArr=points.split(",");var semiColon=/;/g;var min=/\\'/g;var sec=/\\"/g;var symbol,point,label,desc,size,ptColor,outlineColor;for(i=0;i<pointArr.length;i++){var pointItems=pointArr[i].split("|");if(pointItems.length>=4&&pointItems.length<7){if(pointItems[0]=="s")
size=7;else if(pointItems[0]=="l")
size=21;else
size=14;if(pointItems[1]=="b"){ptColor=new Color([0,0,255,0.6]);outlineColor=new Color([0,0,200]);}else if(pointItems[1]=="g"){ptColor=new Color([0,255,0,0.6]);outlineColor=new Color([0,150,5]);}else if(pointItems[1]=="y"){ptColor=new Color([100,100,100,0.6]);outlineColor=new Color([100,100,100]);}else{ptColor=new Color([255,0,0,0.6]);outlineColor=new Color([255,0,10]);}
symbol=new SimpleMarkerSymbol(SimpleMarkerSymbol.STYLE_CIRCLE,size,new SimpleLineSymbol(SimpleLineSymbol.STYLE_SOLID,outlineColor,1),ptColor);if(pointItems.length>4)
label=pointItems[4].replace(semiColon,",").replace(min,"'").replace(sec,"\"");else
label="Way Point";if(pointItems.length>5)
desc=pointItems[5].replace(semiColon,",").replace(min,"'").replace(sec,"\"");else
desc="";point=new Point(parseFloat(pointItems[2]),parseFloat(pointItems[3]),new SpatialReference({wkid:wkid}));}else if(pointItems.length>6){if(pointItems[4].indexOf("h")>-1){var rgba=pointItems[2].split(";");rgba.push(parseFloat(pointItems[3]));ptColor=new Color(rgba);outlineColor=new Color("#"+pointItems[4].substr(1));rgba=null;}else{ptColor=new Color("#"+parseInt(pointItems[2]).toString(16));outlineColor=new Color("#"+parseInt(pointItems[4]).toString(16));}
symbol=new SimpleMarkerSymbol(SimpleMarkerSymbol.STYLE_CIRCLE,pointItems[1],new SimpleLineSymbol(SimpleLineSymbol.STYLE_SOLID,outlineColor,1),ptColor);point=new Point(parseFloat(pointItems[6]),parseFloat(pointItems[7]),new SpatialReference({wkid:wkid}));if(pointItems.length>8)
label=pointItems[8].replace(semiColon,",").replace(min,"'").replace(sec,"\"");else
label="Way Point";if(pointItems.length>9)
desc=pointItems[9].replace(semiColon,",").replace(min,"'").replace(sec,"\"");else
desc="";}
else{alert("Could not add all of the Way Points. This can happen if a long map URL was emailed.","Note",null,true,true);return;}
addPoint(point,label,desc,symbol);}
label=null;point=null;symbol=null;ptColor=null;outlineColor=null;pointArr=null;pointItems=null;});},getMapLink:function(){var url;if(window.location.href.indexOf("&")!=-1)
url=window.location.href.substring(0,window.location.href.indexOf("&"));else
url=window.location.href;url=url.substring(0,url.indexOf("index"));url+=app+"/index.aspx?";url+="prj="+wkid+"&extent="+parseInt(map.extent.xmin)+","+parseInt(map.extent.ymin)+","+parseInt(map.extent.xmax)+","+parseInt(map.extent.ymax);var layers=this.mlGetLayers();if(layers)url+=layers;var waypts=this.mlGetPoints();if(waypts)url+=waypts;if(typeof getHB1298Points==="function"){var hb1298pts=getHB1298Points();if(hb1298pts&&hb1298pts!="")url+=hb1298pts;};return url;}}});