var identifyParams=null;var tasks;var clickPoint;var features=[];var numDatabaseCalls=0;var processedDatabaseCalls=0;var folder=[];var identifyGroup;var theEvt;var theResults;var identifyGroups=[];var identifyLayers={};var groupContent={};var identifyLayerIds=[];var elevation_url=null;var show_elevation=false;var polySymbol,pointSymbol,lineSymbol;var addToTop=30;var lastTitle="";var lastIDGroup="";require(["esri/tasks/IdentifyParameters","esri/symbols/SimpleLineSymbol","esri/symbols/SimpleFillSymbol","esri/symbols/PictureMarkerSymbol","dojo/_base/Color"],function(IdentifyParameters,SimpleLineSymbol,SimpleFillSymbol,PictureMarkerSymbol,Color){identifyParams=new IdentifyParameters();identifyParams.tolerance=5;identifyParams.returnGeometry=true;identifyParams.layerOption=IdentifyParameters.LAYER_OPTION_ALL;polySymbol=new SimpleFillSymbol(SimpleFillSymbol.STYLE_SOLID,new SimpleLineSymbol(SimpleLineSymbol.STYLE_SOLID,new Color([255,0,0]),1),new Color([125,125,125,0.35]));pointSymbol=new PictureMarkerSymbol("assets/images/i_flag.png",40,40);lineSymbol=new SimpleLineSymbol(SimpleLineSymbol.STYLE_SOLID,new Color([255,0,10]),1);});function readSettingsWidget(){map.infoWindow.on("hide",function(event){map.infoWindow.setTitle("");});document.title=app;var settingsFile=app+"/SettingsWidget.xml?v="+ndisVer;var xmlhttp=createXMLhttpRequest();xmlhttp.onreadystatechange=function(){if(xmlhttp.readyState==4&&xmlhttp.status==200){try{var xmlDoc=createXMLdoc(xmlhttp);settings={};var use_gmus=xmlDoc.getElementsByTagName("use_gmus")[0]&&xmlDoc.getElementsByTagName("use_gmus")[0].childNodes[0].nodeValue=="true"?1:0;if(use_gmus){settings.useGMUs=true;if(!xmlDoc.getElementsByTagName("gmu_url")[0])
alert("Missing tag: gmu_url in "+app+"/SettingsWidget.xml","Data Error");else
settings.elkUrl=xmlDoc.getElementsByTagName("gmu_url")[0].childNodes[0].nodeValue;if(!xmlDoc.getElementsByTagName("gmu_field")[0])
alert("Missing tag: gmu_field in "+app+"/SettingsWidget.xml","Data Error");else
settings.elkField=xmlDoc.getElementsByTagName("gmu_field")[0].childNodes[0].nodeValue;if(!xmlDoc.getElementsByTagName("sheep_gmu_url")[0])
alert("Missing tag: sheep_gmu_url in "+app+"/SettingsWidget.xml","Data Error");else
settings.sheepUrl=xmlDoc.getElementsByTagName("sheep_gmu_url")[0].childNodes[0].nodeValue;if(!xmlDoc.getElementsByTagName("sheep_gmu_field")[0])
alert("Missing tag: sheep_gmu_field in "+app+"/SettingsWidget.xml","Data Error");else
settings.sheepField=xmlDoc.getElementsByTagName("sheep_gmu_field")[0].childNodes[0].nodeValue;if(!xmlDoc.getElementsByTagName("goat_gmu_url")[0])
alert("Missing tag: goat_gmu_url in "+app+"/SettingsWidget.xml","Data Error");else
settings.goatUrl=xmlDoc.getElementsByTagName("goat_gmu_url")[0].childNodes[0].nodeValue;if(!xmlDoc.getElementsByTagName("goat_gmu_field")[0])
alert("Missing tag: goat_gmu_field in "+app+"/SettingsWidget.xml","Data Error");else
settings.goatField=xmlDoc.getElementsByTagName("goat_gmu_field")[0].childNodes[0].nodeValue;}
else{settings.useGMUs=false;}
require(["dojo/query","dojo/dom-construct","dojo/on","dojo/dom","dojo/domReady!"],function(query,domConstruct,on,dom){query("div.titleButton.arrow.hidden",map.infoWindow.domNode).on("click",placeIdGroupCombo);var actionlist=domConstruct.create("span",{"class":"actionList"},map.infoWindow.domNode);domConstruct.create("a",{"id":"zoomTo","class":"action","innerHTML":"Zoom To","href":"javascript:void(0);"},query(".actionList",map.infoWindow.domNode)[0]);on(query(".actionList #zoomTo")[0],"click",zoomToPt);var driving_directions=xmlDoc.getElementsByTagName("driving_directions")[0]&&xmlDoc.getElementsByTagName("driving_directions")[0].childNodes[0].nodeValue=="true"?1:0;if(driving_directions){domConstruct.create("a",{"style":"padding-left:20px","class":"action","id":"dirLink","innerHTML":"Directions","href":"javascript:void(0);"},query(".actionList",map.infoWindow.domNode)[0]);on(dom.byId("dirLink"),"click",getDirections);}
if(xmlDoc.getElementsByTagName("elevation")[0]&&xmlDoc.getElementsByTagName("elevation")[0].firstChild.nodeValue)
show_elevation=xmlDoc.getElementsByTagName("elevation")[0].firstChild.nodeValue=="true"?1:0;if(show_elevation&&xmlDoc.getElementsByTagName("elevation_url")[0]){if(xmlDoc.getElementsByTagName("elevation_url")[0].firstChild.nodeValue)
elevation_url=xmlDoc.getElementsByTagName("elevation_url")[0].firstChild.nodeValue;else alert("Missing elevation_url tag in SettingsWidget.xml.","Data Error");}
domConstruct.create("div",{"class":"action","id":"identifyPoint","innerHTML":"Loading lat, long..."},query(".actionList",map.infoWindow.domNode)[0]);query("div.titleButton.close",map.infoWindow.domNode).on("click",clearContent);on(query("div.esriMobileNavigationItem.left")[0],"click",clearContent);});folder=xmlDoc.getElementsByTagName("folder");for(var f=0;f<folder.length;f++)
{if(f==0)identifyGroup=folder[f].getAttribute("label");identifyGroups.push(folder[f].getAttribute("label"));identifyLayerIds[identifyGroups[f]]=[];var layer=folder[f].getElementsByTagName("layer");identifyLayers[identifyGroups[f]]=new Object();if(folder[f].getElementsByTagName("desc")[0])
identifyLayers[identifyGroups[f]].desc=folder[f].getElementsByTagName("desc")[0].firstChild.nodeValue;var label="missing label";for(var i=0;i<layer.length;i++){if(!layer[i].getAttribute("label"))
alert("Error in "+app+"/SettingsWidget.xml. Missing label in folder: "+identifyGroups[f]+".","Data Error");else
label=layer[i].getAttribute("label");identifyLayers[identifyGroups[f]][label]=new Object();var found=false;if(!layer[i].getElementsByTagName("url")[0]||!layer[i].getElementsByTagName("id")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing url or id in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else{for(var j=0;j<identifyLayerIds[identifyGroups[f]].length;j++){if(identifyLayerIds[identifyGroups[f]][j].url==layer[i].getElementsByTagName("url")[0].childNodes[0].nodeValue&&identifyLayerIds[identifyGroups[f]][j].geometry==layer[i].getElementsByTagName("geometry")[0].childNodes[0].nodeValue.toLowerCase()){identifyLayerIds[identifyGroups[f]][j].ids.push(layer[i].getElementsByTagName("id")[0].childNodes[0].nodeValue);found=true;}}}
if(!found){if(!layer[i].getElementsByTagName("url")[0]||!layer[i].getElementsByTagName("id")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing url or id in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else{identifyLayerIds[identifyGroups[f]].push({url:layer[i].getElementsByTagName("url")[0].childNodes[0].nodeValue,ids:new Array(layer[i].getElementsByTagName("id")[0].childNodes[0].nodeValue),geometry:layer[i].getElementsByTagName("geometry")[0].childNodes[0].nodeValue.toLowerCase(),id_vis_only:folder[f].getAttribute("id_vis_only")&&folder[f].getAttribute("id_vis_only").toLowerCase()=="true"?true:false});}}
if(layer[i].getElementsByTagName("database")[0]){if(!layer[i].getElementsByTagName("url")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing url in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].url=layer[i].getElementsByTagName("url")[0].childNodes[0].nodeValue;if(!layer[i].getElementsByTagName("id")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing id in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].id=layer[i].getElementsByTagName("id")[0].childNodes[0].nodeValue;if(!layer[i].getElementsByTagName("geometry")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing geometry in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].geometry=layer[i].getElementsByTagName("geometry")[0].childNodes[0].nodeValue;if(!layer[i].getElementsByTagName("fields")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing fields in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].fields=layer[i].getElementsByTagName("fields")[0].childNodes[0].nodeValue.split(",");if(!layer[i].getElementsByTagName("displaynames")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing displaynames in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].displaynames=layer[i].getElementsByTagName("displaynames")[0].childNodes[0].nodeValue.split(",");if(layer[i].getElementsByTagName("position")[0])
identifyLayers[identifyGroups[f]][label].position=layer[i].getElementsByTagName("position")[0].childNodes[0].nodeValue;else
identifyLayers[identifyGroups[f]][label].position=0;if(!layer[i].getElementsByTagName("database")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing database in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error")
else
identifyLayers[identifyGroups[f]][label].database=layer[i].getElementsByTagName("database")[0].childNodes[0].nodeValue;if(!layer[i].getElementsByTagName("filename")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing filename in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].filename=layer[i].getElementsByTagName("filename")[0].childNodes[0].nodeValue;if(layer[i].getElementsByTagName("one2one_fields")[0]&&layer[i].getElementsByTagName("one2one_fields")[0].childNodes.length>0)
identifyLayers[identifyGroups[f]][label].one2one_fields=layer[i].getElementsByTagName("one2one_fields")[0].childNodes[0].nodeValue.split(",");if(layer[i].getElementsByTagName("one2one_display")[0]&&layer[i].getElementsByTagName("one2one_display")[0].childNodes.length>0)
identifyLayers[identifyGroups[f]][label].one2one_display=layer[i].getElementsByTagName("one2one_display")[0].childNodes[0].nodeValue.split(",");if(layer[i].getElementsByTagName("one2many_fields")[0]&&layer[i].getElementsByTagName("one2many_fields")[0].childNodes.length>0)
identifyLayers[identifyGroups[f]][label].one2many_fields=layer[i].getElementsByTagName("one2many_fields")[0].childNodes[0].nodeValue.split(",");}
else{if(!layer[i].getElementsByTagName("url")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing url in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].url=layer[i].getElementsByTagName("url")[0].childNodes[0].nodeValue;if(!layer[i].getElementsByTagName("id")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing id in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].id=layer[i].getElementsByTagName("id")[0].childNodes[0].nodeValue;if(!layer[i].getElementsByTagName("geometry")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing geometry in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].geometry=layer[i].getElementsByTagName("geometry")[0].childNodes[0].nodeValue;if(!layer[i].getElementsByTagName("fields")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing fields in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].fields=layer[i].getElementsByTagName("fields")[0].childNodes[0].nodeValue.split(",");if(!layer[i].getElementsByTagName("displaynames")[0])
alert("Error in "+app+"/SettingsWidget.xml. Missing displaynames in folder: "+identifyGroups[f]+" for layer: "+label+".","Data Error");else
identifyLayers[identifyGroups[f]][label].displaynames=layer[i].getElementsByTagName("displaynames")[0].childNodes[0].nodeValue.split(",");if(label=="Big Game GMU"){identifyLayers[identifyGroups[f]]["Bighorn GMU"]=new Object();identifyLayers[identifyGroups[f]]["Bighorn GMU"].url=settings.sheepUrl.slice(0,settings.sheepUrl.length-2);identifyLayers[identifyGroups[f]]["Bighorn GMU"].id=settings.sheepUrl.slice(settings.sheepUrl.length-1);identifyLayers[identifyGroups[f]]["Bighorn GMU"].geometry="polygon";identifyLayers[identifyGroups[f]]["Bighorn GMU"].fields=[settings.sheepField];identifyLayers[identifyGroups[f]]["Bighorn GMU"].displaynames=["GMU Number"];identifyLayers[identifyGroups[f]]["Goat GMU"]=new Object();identifyLayers[identifyGroups[f]]["Goat GMU"].url=settings.goatUrl.slice(0,settings.goatUrl.length-2);identifyLayers[identifyGroups[f]]["Goat GMU"].id=settings.goatUrl.slice(settings.goatUrl.length-1);identifyLayers[identifyGroups[f]]["Goat GMU"].geometry="polygon";identifyLayers[identifyGroups[f]]["Goat GMU"].fields=[settings.goatField];identifyLayers[identifyGroups[f]]["Goat GMU"].displaynames=["GMU Number"];}}}}
setIdGroupCombo();document.getElementById("loading").style.display="none";}
catch(e){alert("Error reading "+app+"/SettingsWidget.xml in javascriptM/identify.js readSettingsWidget(): "+e.message,"Data Error",e);hideLoading("");}}
else if(xmlhttp.status===404){alert("Error: Missing "+app+"/settingsWidget.xml file.","Data Error");hideLoading();}
else if(xmlhttp.readyState===4&&xmlhttp.status===500){alert("Error reading "+app+"/settingsWidget.xml.","Code Error");hideLoading();}};xmlhttp.open("GET",settingsFile,true);xmlhttp.send();}
function clearContent(){map.infoWindow.setContent("");if(map.getLayer("mapDiv_graphics"))
map.removeLayer(map.getLayer("mapDiv_graphics"));}
function doIdentify(evt){if(evt.Event)evt=evt.Event;if(measuring)return;if(drawing){drawing=false;return;}
if(dragging)return;var map=this;require(["dojo/dom-construct","dojo/query","dojo/dom","dojo/on","dojo/domReady!"],function(domConstruct,query,dom,on){clickPoint=getScreenClick(evt);if(map.infoWindow.isShowing&&lastTitle==map.infoWindow._title.innerHTML){map.infoWindow.hide();if(navigator.userAgent.indexOf('Android')!=-1)evt.stopImmediatePropagation();map.emit("click",{bubbles:true,cancelable:true,Event:evt});return;}
else if((navigator.userAgent.indexOf('Android')!=-1)&&(map.infoWindow._title.innerHTML==""||map.infoWindow._title.innerHTML=="No Information"))evt.stopImmediatePropagation();numDatabaseCalls=0;processedDatabaseCalls=0;features=[];theEvt=evt;showLoading();if(groupContent["Way Point"])delete groupContent["Way Point"];for(var i=0;i<identifyGroups.length;i++){groupContent[identifyGroups[i]]=null;}
if(map.infoWindow._title.innerHTML!=""&&map.infoWindow._title.innerHTML!="No Information"){if(identifyGroup!="Way Point")lastIDGroup=identifyGroup;identifyGroup="Way Point";groupContent["Way Point"]=map.infoWindow._contentPane.innerHTML;if(idGroupCombo.getOptions("Way Point")==null){idGroupCombo.addOption({value:"Way Point",label:"Way Point"});idGroupCombo.startup();}
idGroupCombo.set("displayedValue","Way Point");var supportsOrientationChange="onorientationchange"in window,orientationEvent=supportsOrientationChange?"orientationchange":"resize";window.addEventListener(orientationEvent,function(){showLoading();setTimeout(resizeTextBox(document.getElementById("wayPtDesc")),500);},false);lastTitle=map.infoWindow._title.innerHTML;}
else{map.infoWindow.hide();map.infoWindow.setTitle("Loading...");map.infoWindow.setContent("<p align='center'>Loading...</p>");if(identifyGroup=="Way Point")identifyGroup=lastIDGroup;if(idGroupCombo.getOptions("Way Point")){idGroupCombo.removeOption("Way Point");}}
dom.byId("identifyPoint").innerHTML="Loading lat, long...";if(elevation_url){if(query(".actionList #elevation",map.infoWindow.domNode)[0]){domConstruct.empty(query(".actionList #elevation",map.infoWindow.domNode)[0]);domConstruct.place(domConstruct.toDom("Elevation: loading..."),query(".actionList #elevation",map.infoWindow.domNode)[0]);}
else{domConstruct.create("span",{"class":"action","id":"elevation","innerHTML":"Elevation: loading..."},query(".actionList",map.infoWindow.domNode)[0]);}}
showIdentify();displayContent();});}
function displayContent(){require(["esri/tasks/IdentifyParameters","esri/tasks/IdentifyTask","dojo/_base/array","dojo/DeferredList","dojo/_base/Deferred"],function(IdentifyParameters,IdentifyTask,array,DeferredList,Deferred){if(groupContent[identifyGroup]){map.infoWindow.setContent(groupContent[identifyGroup]);if(identifyGroup=="Way Point")
resizeTextBox(document.getElementById('wayPtDesc'));getIdentifyFooter();hideLoading("");return;}
var task;identifyParams.geometry=clickPoint;identifyParams.mapExtent=map.extent;identifyParams.width=map.width;identifyParams.height=map.height;var deferreds=array.map(identifyLayerIds[identifyGroup],function(item){if(item)
{task=new IdentifyTask(item.url);identifyParams.layerIds=item.ids.slice();if(item.geometry!="polygon"){if(map.getScale()<=36112)
identifyParams.tolerance=25;else if(map.getScale()<=288895)
identifyParams.tolerance=20;else
identifyParams.tolerance=10;}
else
identifyParams.tolerance=1;if(item.id_vis_only){var layers=map.getLayersVisibleAtScale(map.getScale());var url=item.url;if(item.url[item.url.length-1]=="/")url=item.url.substr(0,item.url.length-1);vis_layers=[];array.forEach(layers,function(layer){if(layer.url==url){if(layer.visible==true){for(var i=0;i<identifyParams.layerIds.length;i++){if(layer.layerInfos[identifyParams.layerIds[i]].parentLayerId==-1||layer.layerInfos[identifyParams.layerIds[i]].visible==false){if(layer.layerInfos[identifyParams.layerIds[i]].visible==true)
vis_layers.push(identifyParams.layerIds[i]);}
else if(layer.layerInfos[layer.layerInfos[identifyParams.layerIds[i]].parentLayerId].parentLayerId==-1||layer.layerInfos[layer.layerInfos[identifyParams.layerIds[i]].parentLayerId].visible==false){if(layer.layerInfos[layer.layerInfos[identifyParams.layerIds[i]].parentLayerId].visible==true)
vis_layers.push(identifyParams.layerIds[i]);}
else if(layer.layerInfos[layer.layerInfos[layer.layerInfos[identifyParams.layerIds[i]].parentLayerId].parentLayerId].parentLayerId==-1||layer.layerInfos[layer.layerInfos[layer.layerInfos[identifyParams.layerIds[i]].parentLayerId].parentLayerId].visible==false){if(layer.layerInfos[layer.layerInfos[layer.layerInfos[identifyParams.layerIds[i]].parentLayerId].parentLayerId].visible==true)
vis_layers.push(identifyParams.layerIds[i]);}}
identifyParams.layerIds=vis_layers;identifyParams.layerOption=IdentifyParameters.LAYER_OPTION_ALL;}
else{identifyParams.layerIds=[];identifyParams.layerOption=IdentifyParameters.LAYER_OPTION_VISIBLE;}}});}
else identifyParams.layerOption=IdentifyParameters.LAYER_OPTION_ALL;if(settings.elkUrl&&item.url==settings.elkUrl.slice(0,settings.elkUrl.lastIndexOf("/")+1)&&gmu!="Big Game GMU"){var index=identifyParams.layerIds.indexOf(settings.elkUrl.slice(settings.elkUrl.lastIndexOf("/")+1));if(index>-1)identifyParams.layerIds.splice(index,1);}
return task.execute(identifyParams,identifySuccess,handleQueryError);}});if(identifyGroup=="GMU and Land Management"){if(gmu=="Bighorn GMU"){identifyParams.tolerance=1;identifyParams.layerIds=[settings.sheepUrl.slice(settings.sheepUrl.lastIndexOf("/")+1)];task=new IdentifyTask(settings.sheepUrl.slice(0,settings.sheepUrl.lastIndexOf("/")+1));deferreds.push(task.execute(identifyParams,identifySuccess,handleQueryError));}
else if(gmu=="Goat GMU"){identifyParams.tolerance=1;identifyParams.layerIds=[settings.goatUrl.slice(settings.goatUrl.lastIndexOf("/")+1)];task=new IdentifyTask(settings.goatUrl.slice(0,settings.goatUrl.lastIndexOf("/")+1));deferreds.push(task.execute(identifyParams,identifySuccess,handleQueryError));}}
var dlist=new DeferredList(deferreds);dlist.then(handleQueryResults);});}
function identifySuccess(e){}
function handleQueryError(e){if(e.details)
alert("Error in identify.js/doIdentify.  "+e.details+" "+e.message+" Check SettingsWidget.xml urls.","Data Error");else
alert("Error in identify.js/doIdentify.  "+e.message+" Check SettingsWidget.xml urls.","Data Error");hideLoading("");}
function handleQueryResults(results){require(["dojo/_base/array"],function(array){try{if(!results){alert("Error in identify.js/handleQueryResults. IdentifyTask returned null.","Data Error");return;}
theResults=results;var title,title_subject;array.forEach(results,function(result){if(result[1]&&result[1].length>0){array.forEach(result[1],function(r){if(typeof identifyLayers[identifyGroup][r.layerName]!='undefined')
if(typeof identifyLayers[identifyGroup][r.layerName].database!='undefined')numDatabaseCalls++;});}});index=0;while(XMLHttpRequestObjects.length>0){XMLHttpRequestObjects.pop();}
var notfound=true;var i,j;function findGroupInResults(results){for(i=0;i<results.length;i++){if(results[i][1]&&results[i][1].length>0){for(j=0;j<results[i][1].length;j++){if(identifyLayers[identifyGroup][results[i][1][j].layerName]){notfound=false;return;}}}}}
findGroupInResults(results);if(notfound)title="No "+identifyGroup;else if(results[i][1][j].displayFieldName=="WATERCODE"){title="";for(var k=0;k<results[i][1].length;k++){if(results[i][1][k].layerName.toUpperCase()=="ALL LAKES"){title=results[i][1][k].value;break;}}
if(title=="")title=results[i][1][j].layerName;}
else if(results[i][1][j].displayFieldName=="LOC_ID")title=results[i][1][j].layerName;else if(results[i][1][j].displayFieldName=="GMUID")title="GMU "+results[i][1][j].feature.attributes[results[i][1][j].displayFieldName];else if(results[i][1][j].layerName.indexOf("Land Management")!=-1&&results[i][1][j].feature.attributes[results[i][1][j].displayFieldName]=="")
title=results[i][1][j].feature.attributes["MANAGER"];else if(results[i][1][j].layerName.indexOf("Mule Deer")>-1)title="Mule Deer Ranges";else if(results[i][1][j].layerName.indexOf("Elk")>-1)title="Elk Ranges";else title=results[i][1][j].feature.attributes[results[i][1][j].displayFieldName];map.infoWindow.setTitle(title);lastTitle=title;var tmpStr;var str=getIdentifyHeader(identifyGroup);array.forEach(results,function(result){if(result[1].length>0){array.forEach(result[1],function(r){var feature=r.feature;feature.attributes.layerName=r.layerName;if(typeof identifyLayers[identifyGroup][r.layerName]!='undefined'){if(typeof identifyLayers[identifyGroup][r.layerName].database!='undefined'){try{createMultiXMLhttpRequest();var url=app+"/"+identifyLayers[identifyGroup][r.layerName].database+"?v="+ndisVer+"&key="+r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[0]];XMLHttpRequestObjects[index].open("GET",url,true);XMLHttpRequestObjects[index].onreadystatechange=function(arrIndex){return function(){if(XMLHttpRequestObjects[arrIndex].readyState==4){if(XMLHttpRequestObjects[arrIndex].status==200){tmpStr=r.layerName+"</strong><div style='padding-left: 10px;'>";var xmlDoc=createXMLdoc(XMLHttpRequestObjects[arrIndex]);for(i=0;i<identifyLayers[identifyGroup][r.layerName].displaynames.length;i++){if((i>0&&r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]&&r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]!==" "&&r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]!=="Null"&&r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]!=="")){if(r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]].substring(0,4)=="http")
tmpStr+="<a href='"+r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]+"' target='_blank'>"+identifyLayers[identifyGroup][r.layerName].displaynames[i]+"</a>";else{if((r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]].substring(0,7)=="<a href")&&(r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]].indexOf("target")==-1))
tmpStr+=identifyLayers[identifyGroup][r.layerName].displaynames[i]+": "+r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]].replace(">"," target='_blank'>");else
tmpStr+=identifyLayers[identifyGroup][r.layerName].displaynames[i]+": "+r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]];}
tmpStr+="<br/>";}
if(identifyLayers[identifyGroup][r.layerName].position==i){if(typeof identifyLayers[identifyGroup][r.layerName].one2one_fields!="undefined"){for(j=0;j<identifyLayers[identifyGroup][r.layerName].one2one_fields.length;j++){if(xmlDoc.getElementsByTagName(identifyLayers[identifyGroup][r.layerName].one2one_fields[j]).length>0){var one2one_field=xmlDoc.getElementsByTagName(identifyLayers[identifyGroup][r.layerName].one2one_fields[j])[0];if((one2one_field.getElementsByTagName("linkname").length>0)&&(one2one_field[h].getElementsByTagName("linkurl").length>0)){tmpStr+=identifyLayers[identifyGroup][r.layerName].one2one_display[j]+": ";tmpStr+="<a href='"+one2one_field.getElementsByTagName("linkurl")[0].firstChild.nodeValue+"'>"+one2one_field.getElementsByTagName("linkname")[0].firstChild.nodeValue+"</a>";tmpStr+="<br/>";}
else if(one2one_field.childNodes.length>0){tmpStr+=identifyLayers[identifyGroup][r.layerName].one2one_display[j]+": ";tmpStr+=one2one_field.childNodes[0].nodeValue;tmpStr+="<br/>";}}}}
if(typeof identifyLayers[identifyGroup][r.layerName].one2many_fields!="undefined"){for(j=0;j<identifyLayers[identifyGroup][r.layerName].one2many_fields.length;j++){var one2many=xmlDoc.getElementsByTagName(identifyLayers[identifyGroup][r.layerName].one2many_fields[j]);tmpStr+=identifyLayers[identifyGroup][r.layerName].displaynames[0]+":<ul style='margin-top: 0px; margin-bottom: 0px;'>";for(var h=0;h<one2many.length;h++){if((one2many[h].getElementsByTagName("linkname").length>0)&&(one2many[h].getElementsByTagName("linkurl").length>0)){tmpStr+="<li><a href='"+one2many[h].getElementsByTagName("linkurl")[0].firstChild.nodeValue+"' target='_blank'>"+one2many[h].getElementsByTagName("linkname")[0].firstChild.nodeValue+"</a></li>";}
else{tmpStr+="<li>"+one2many[h].childNodes[0].nodeValue+"</li>";}}
tmpStr+="</ul style='margin-bottom: 0px; margin-top: 0px;'>";}}}}
tmpStr+="</div><br/>"
processedDatabaseCalls++;if(str.indexOf(tmpStr)==-1){str+="<div><strong>"+tmpStr;groupContent[identifyGroup]=str;map.infoWindow.setContent(str);}
features.push(r.feature);}
else{if(XMLHttpRequestObjects[arrIndex].status==404){alert("Identify failed. File not found: "+url,"Data Error");processedDatabaseCalls=numDatabaseCalls;displayInfoWindow();}
else{alert("Identify failed for call to "+url+". Make sure it exists and does not have errors. Must be in the same directory as index.html or a lower directory. XMLHttpRequestObjects["+arrIndex+"].status was "+XMLHttpRequestObjects[arrIndex].status,"Data Error");processedDatabaseCalls=numDatabaseCalls;displayInfoWindow();}}
var isAllComplete=true;for(var i=0;i<numDatabaseCalls;i++){if((!XMLHttpRequestObjects[i])||(XMLHttpRequestObjects[i].readyState!==4)){isAllComplete=false;break;}}
if(isAllComplete){displayInfoWindow();}}}}(index);XMLHttpRequestObjects[index].send();}
catch(error){alert("Identify on "+r.layerName+" failed with error: "+error.message+" in javascript/identify.js handleQueryResults().","Data Error");console.log(error.message);hideLoading("");}}
else{tmpStr=r.layerName+"</strong><div style='padding-left: 10px;'>";var first=true;for(i=0;i<identifyLayers[identifyGroup][r.layerName].displaynames.length;i++){if((r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]&&r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]!==" "&&r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]!=="Null"&&r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]!=="")){if(first)first=false;else tmpStr+="<br/>";if(r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]].substring(0,4)=="http")
tmpStr+="<a href='"+r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]]+"' target='_blank'>"+identifyLayers[identifyGroup][r.layerName].displaynames[i]+"</a>";else
tmpStr+=identifyLayers[identifyGroup][r.layerName].displaynames[i]+": "+r.feature.attributes[identifyLayers[identifyGroup][r.layerName].fields[i]];}}
tmpStr+="</div></div><br/>";if(str.indexOf(tmpStr)==-1){str+="<div><strong>"+tmpStr;groupContent[identifyGroup]=str;map.infoWindow.setContent(str);}
features.push(r.feature);}}});}});displayInfoWindow();}
catch(e){alert(e.message+" in javascript/identify.js handleQueryResults().","Code Error",e);}});}
function highlightFeature(id){require(["esri/graphic","esri/layers/GraphicsLayer"],function(Graphic,GraphicsLayer){var highlightSymbol;if(features[id].geometry.type==="polygon"){highlightSymbol=polySymbol;}
else if(features[id].geometry.type==="point"){highlightSymbol=pointSymbol;}
else if(features[id].geometry.type==="line"){highlightSymbol=lineSymbol;}
var identifyGraphicsLayer=newGraphicsLayer();identifyGraphicsLayer.id="identifygraphics";for(var i=0;i<features.length;i++){if(features[i].attributes.layerName==features[id].attributes.layerName)
identifyGraphicsLayer.add(new Graphic(features[id].geometry,highlightSymbol));}
map.addLayer(identifyGraphicsLayer);identifyGraphicsLayer=null;highlightSymbol=null;});}
function removeHighlight(){if(map.getLayer("identifygraphics"))
map.removeLayer(map.getLayer("identifygraphics"));}
function showIdentify(){map.infoWindow.show(clickPoint);if(map.getLayer("mapDiv_graphics")){map.getLayer("mapDiv_graphics").clear();}
require(["dojo/query"],function(dojoquery){if(dojoquery(".top")&&dojoquery(".top")[0].outerHTML.indexOf("hidden")>-1){var top=parseInt(dojoquery(".esriPopupMobile")[0].style.top)-addToTop;dojoquery(".esriPopupMobile")[0].style.top=top+"px";}});}
function getIdentifyHeader(name){if(identifyLayers[name].desc)
return"<div class='esriPopupItemTitle'>"+name+" found at map click:</div><br/><p style='font-style:italic;top:-15px;position:relative;'>"+identifyLayers[name].desc+"</p>";else
return"<div class='esriPopupItemTitle'>"+name+" found at map click:</div>";}
function getIdentifyFooter(){require(["esri/geometry/webMercatorUtils","esri/SpatialReference","esri/tasks/ProjectParameters","esri/tasks/GeometryService","dojo/dom"],function(webMercatorUtils,SpatialReference,ProjectParameters,GeometryService,dom){try{var geoPt;geoPt=webMercatorUtils.webMercatorToGeographic(clickPoint);dom.byId("identifyPoint").innerHTML="Lat Long: "+geoPt.y.toFixed(5)+" N, "+geoPt.x.toFixed(5)+" W";;if(elevation_url){require(["esri/request"],function(esriRequest){var ext='{"xmin":'+map.extent.xmin+',"ymin":'+map.extent.ymin+',"xmax":'+map.extent.xmax+',"ymax":'+map.extent.ymax+',"spatialReference":{"wkid":102100,"latestWkid":102100}}';var layersRequest=esriRequest({url:elevation_url+"/identify",content:{f:"json",geometry:JSON.stringify(clickPoint),geometryType:"esriGeometryPoint",tolerance:"5",mapExtent:ext,sr:"102100",imageDisplay:map.width+","+map.height+",96",returnGeometry:false},handleAs:"json",callbackParamName:"callback"});layersRequest.then(function(response){require(["dojo/dom-attr","dojo/dom-construct","dojo/query","dojo/dom","dojo/on","dojo/domReady!"],function(domAttr,domConstruct,query,dom,on){if(query(".actionList #elevation",map.infoWindow.domNode)[0]){domConstruct.empty(query(".actionList #elevation",map.infoWindow.domNode)[0]);domConstruct.place(domConstruct.toDom("Elevation: "+Math.round(response.results[0].attributes["Pixel Value"])+" ft "+Math.round(response.results[0].attributes["Pixel Value"]*0.3048)+" m"),query(".actionList #elevation",map.infoWindow.domNode)[0]);}
else{domConstruct.create("span",{"class":"action","id":"elevation","innerHTML":"Elevation: "+Math.round(response.results[0].attributes["Pixel Value"])+" ft "+Math.round(response.results[0].attributes["Pixel Value"]*0.3048)+" m"},query(".actionList",map.infoWindow.domNode)[0]);}});},function(error){require(["dojo/dom-attr","dojo/dom-construct","dojo/query","dojo/dom","dojo/on","dojo/domReady!"],function(domAttr,domConstruct,query,dom,on){if(query(".actionList #elevation",map.infoWindow.domNode)[0]){domConstruct.empty(query(".actionList #elevation",map.infoWindow.domNode)[0]);domConstruct.place(domConstruct.toDom("Elevation: data not available"),query(".actionList #elevation",map.infoWindow.domNode)[0]);}
else{domConstruct.create("span",{"class":"action","id":"elevation","innerHTML":"Elevation: data not available"},query(".actionList",map.infoWindow.domNode)[0]);}});hideLoading("");});});}}
catch(e){alert(e.message+" in javascript/identify.js getIdentifyFooter().","Code Error",e);}});}
function changeIdentifyGroup(sel){identifyGroup=sel.get("displayedValue");map.infoWindow.setContent("<p align='center'>Loading...</p>");features=[];numDatabaseCalls=0;processedDatabaseCalls=0;displayContent();}
var idGroupCombo;function setIdGroupCombo(){require(["dojo/store/Memory","dijit/form/Select"],function(Memory,Select){var idGroupStore=[];for(var i=0;i<identifyGroups.length;i++){idGroupStore.push({value:identifyGroups[i],label:identifyGroups[i]});}
idGroupCombo=new Select({id:"idGroup",name:"feature",value:identifyGroup,sortByLabel:false,labelAttr:"name",maxHeight:-1,style:{height:"36px!important",lineHeight:"22px",fontSize:"17px",color:"black",position:"absolute",top:"0px",left:"40px",display:"block"},onChange:function(){changeIdentifyGroup(this);}},"idGroup");idGroupCombo.set("options",idGroupStore);idGroupCombo.startup();});}
function placeIdGroupCombo(){require(["dojo/dom-construct","dojo/query","dojo/dom-class","dijit/registry"],function(domConstruct,query,domClass,registry){map.infoWindow.setContent(groupContent[identifyGroup]);if(identifyGroup=="Way Point"){resizeTextBox(document.getElementById('wayPtDesc'));query("div.esriMobileNavigationBar",map.domNode)[0].style.overflow="visible";query("div.esriMobileNavigationItem.center",map.domNode)[0].style.display="none";domConstruct.place(idGroupCombo.domNode,query("div.esriMobileNavigationItem.center",map.domNode)[0],"before");registry.byId("idGroup").attr("displayedValue","Way Point");query("div.esriMobileNavigationItem.right1",map.domNode)[0].className="esriMobileNavigationItem right1 hidden";query("div.esriMobileNavigationItem.right2",map.domNode)[0].className="esriMobileNavigationItem right2 hidden";if(document.getElementById("wayPtDesc")){document.getElementById("wayPtDesc").style.height='auto';document.getElementById("wayPtDesc").style.height=document.getElementById("wayPtDesc").scrollHeight+'px';}}
else if(query("div.esriMobileNavigationItem.center",map.domNode).length>0){query("div.esriMobileNavigationItem.center",map.domNode)[0].style.display="none";query("div.esriMobileNavigationItem.right1",map.domNode)[0].className="esriMobileNavigationItem right1 hidden";query("div.esriMobileNavigationItem.right2",map.domNode)[0].className="esriMobileNavigationItem right2 hidden";domConstruct.place(idGroupCombo.domNode,query("div.esriMobileNavigationItem.center",map.domNode)[0],"before");registry.byId("idGroup").attr("displayedValue",identifyGroup);}});}
function displayInfoWindow(){if(numDatabaseCalls==processedDatabaseCalls){numDatabaseCalls=0;processedDatabaseCalls=0;getIdentifyFooter();if(features.length==0){var visible="";if(identifyLayerIds[identifyGroup][0].id_vis_only)visible="visible ";var str;if(identifyLayers[identifyGroup].desc){str="<div><p style='font-style:italic;top:-15px;position:relative;'>"+identifyLayers[identifyGroup].desc+"</p>No "+visible+identifyGroup+" at this point.<br/><br/></div>";groupContent[identifyGroup]=str;}
else{str="<br/><div>No "+visible+identifyGroup+" at this point.<br/><br/></div>"
groupContent[identifyGroup]=str;}
map.infoWindow.setContent(str);}
showIdentify();hideLoading("");}}
function getDirections(evt){require(["esri/geometry/webMercatorUtils"],function(webMercatorUtils){var geoPt=webMercatorUtils.webMercatorToGeographic(clickPoint);var url="http://google.com/maps?output=classic&q="+geoPt.y+","+geoPt.x;window.open(url,"_blank");});}
function zoomToPt(){var level=5;if(map.getLevel()>5)level=map.getLevel();map.centerAndZoom(clickPoint,level);}