Number.prototype.numberFormat=function(decimals,dec_point,thousands_sep){dec_point=typeof dec_point!=='undefined'?dec_point:'.';thousands_sep=typeof thousands_sep!=='undefined'?thousands_sep:',';var parts=this.toFixed(decimals).toString().split(dec_point);parts[0]=parts[0].replace(/\B(?=(\d{3})+(?!\d))/g,thousands_sep);return parts.join(dec_point);}
function mappoint_to_dms(point,leadingZero){var ddPoint=esri.geometry.webMercatorToGeographic(point);var pointArr=dd_to_dms(ddPoint,leadingZero);return pointArr;}
function dd_to_dms(ddPoint,leadingZero){var lonAbs=Math.abs(Math.round(ddPoint.x*1000000.));var latAbs=Math.abs(Math.round(ddPoint.y*1000000.));var degY=Math.floor(latAbs/1000000)+'° ';var minY=Math.floor(((latAbs/1000000)-Math.floor(latAbs/1000000))*60)+'\' ';var secY=Math.floor(Math.floor(((((latAbs/1000000)-Math.floor(latAbs/1000000))*60)-Math.floor(((latAbs/1000000)-Math.floor(latAbs/1000000))*60))*100000)*60/100000)+'"';if(leadingZero&&minY.length==3)minY="0"+minY;if(leadingZero&&secY.length==2)secY="0"+secY;var y=degY+minY+secY;var degX=Math.floor(lonAbs/1000000)+'° ';var minX=Math.floor(((lonAbs/1000000)-Math.floor(lonAbs/1000000))*60)+'\' ';var secX=Math.floor(Math.floor(((((lonAbs/1000000)-Math.floor(lonAbs/1000000))*60)-Math.floor(((lonAbs/1000000)-Math.floor(lonAbs/1000000))*60))*100000)*60/100000)+'"';if(leadingZero&&minX.length==3)minX="0"+minX;if(leadingZero&&secX.length==2)secX="0"+secX;var x=degX+minX+secX;var pointArr=[];pointArr.push(y);pointArr.push(x);return pointArr;}
function mappoint_to_dm(point,leadingZero){ddPoint=esri.geometry.webMercatorToGeographic(point);var pointArr=dd_to_dm(ddPoint,leadingZero);return pointArr;}
function dd_to_dm(ddPoint,leadingZero){var lonAbs=Math.abs(Math.round(ddPoint.x*1000000.));var latAbs=Math.abs(Math.round(ddPoint.y*1000000.));var degY=Math.floor(latAbs/1000000)+'° ';var minY=(((latAbs/1000000)-Math.floor(latAbs/1000000))*60).toFixed(5)+'\' ';if(leadingZero&&minY.indexOf(".")==1)minY="0"+minY;var y=degY+minY;var degX=Math.floor(lonAbs/1000000)+'° ';var minX=(((lonAbs/1000000)-Math.floor(lonAbs/1000000))*60).toFixed(5)+'\' ';if(leadingZero&&minX.indexOf(".")==1)minX="0"+minX;var x=degX+minX;var pointArr=[];pointArr.push(y);pointArr.push(x);return pointArr;}
function dms_or_dm_to_dd(str){var pos,pos2,pointX,pointY;var arr=new Array();pointY=str.substring(0,str.indexOf(","));pointX=str.substring(str.indexOf(",")+1,str.length);pos=pointX.indexOf(":");if(pos==-1){alert("Missing ':'. Must be in the formate 40:0:0,103:0:0 or 40:0,103:0","Warning");return null;}
var degX=Number(pointX.substring(0,pos));if(!((degX>=-110&&degX<=-100)||(degX>=100&&degX<=110))){var tmp;tmp=pointY;pointY=pointX;pointX=tmp;pos=pointX.indexOf(":");degX=Number(pointX.substring(0,pos));}
var secX=0;var minX;pos2=pointX.substring(pos+1).indexOf(":")
if(pos2>-1){minX=Number(pointX.substr(pos+1,pos2));secX=Number(pointX.substring(pos+pos2+2));}
else minX=Number(pointX.substring(pos+1));pointX=Number(degX)+Number(minX)/60+Number(secX)/3600;if(pointX>=100&&pointX<=110)pointX=pointX*-1;pos=pointY.indexOf(":");if(pos==-1){alert("Missing ':'. Must be in the formate 40:0:0,103:0:0 or 40:0,103:0","Warning");return null;}
var degY=Number(pointY.substring(0,pos));var secY=0;var minY;pos2=pointY.substring(pos+1).indexOf(":")
if(pos2>-1){minY=Number(pointY.substr(pos+1,pos2));secY=Number(pointY.substring(pos+pos2+2));}
else minY=Number(pointY.substring(pos+1));pointY=Number(degY)+Number(minY)/60+Number(secY)/3600;label=degY+'° '+minY+'\' ';if(secY>0)label+=secY+'" N, ';else label+=" N, ";if(pointY>=100&&pointY<=110)pointY=pointY*-1;label+=degX+'° '+minX+'\' ';if(secX>0)label+=secX+'" W';else label+=" W";if(!((pointX>=-110&&pointX<=-100)&&(pointY>=35&&pointY<=42))){alert("This point is not in Colorado. Latitude of 35 - 42. Longitude of 100 - 110.","Warning");return null;}
arr.push(pointY,pointX,label);return arr;}
function showLoading(){esri.show(loading);map.disableMapNavigation();map.hideZoomSlider();}
function hideLoading(){esri.hide(loading);map.enableMapNavigation();map.showZoomSlider();}
function removeSearchItem(){if(searchGraphicsCount.length==0)return;var gl=searchGraphicsCount.pop();map.getLayer(gl).setOpacity(0.3);var t=window.setTimeout(function(){map.getLayer(gl).clear();window.clearTimeout(t);gl=null;},2000);if(searchGraphicsCount.length==0){document.getElementById("findClear").style.opacity=.2;document.getElementById("findClear").style.filter="alpha(opacity=20)";}}
function showSearchHelp(){document.getElementById('search_help').style.display='block';}
function hideSearchHelp(){document.getElementById('search_help').style.display='none';}
function loadPage(url){window.location.assign(url);}
function getCookie(cname){if(typeof(Storage)=="undefined")
getCookie2(cname);else{var localStorage;try{localStorage=window.localStorage;}catch(e){alert("Your browser doesn't accept cookies. Failed to read user preferences and bookmarks. See Help/Troubleshooting/Losing Your Saved Preferences for help on how to set your browser to accept cookies.","Warning");return"";}
try{var result=localStorage.getItem(cname);if(!result)return"";else return result;}
catch(e){alert("Your browser doesn't accept cookies. Failed to read user preferences and bookmarks. See Help/Troubleshooting/Losing Your Saved Preferences for help on how to set your browser to accept cookies.","Warning");return"";}}}
function setCookie(cname,cvalue){if(typeof(Storage)=="undefined")
setCookie2(cname);else{var localStorage;try{localStorage=window.localStorage;}catch(e){alert("Your browser doesn't accept cookies. Failed to set user preferences or bookmarks. See Help/Troubleshooting/Losing Your Saved Preferences for help on how to set your browser to accept cookies.","Warning");return"";}
try{localStorage.setItem(cname,cvalue);}
catch(e){if(e.name==='QuotaExceededError'||e.name==='NS_ERROR_DOM_QUOTA_REACHED'||e.code===22){alert("Browser storage full. Try removing some "+app+" bookmarks.","Warning");}
else
alert("Saving user preferences and bookmarks requires non-private browser mode. Please set this mode and try again. Also, this may be caused by your browser not accepting cookies. See Help/Troubleshooting/Losing Your Saved Preferences for help on how to set your browser to accept cookies.","Warning");}}}
function deleteCookie(cname){if(typeof(Storage)=="undefined")
deleteCookie2(cname);else{var localStorage;try{localStorage=window.localStorage;}catch(e){alert("Your browser doesn't accept cookies. Failed to remove user preferences or bookmarks. See Help/Troubleshooting/Losing Your Saved Preferences for help on how to set your browser to accept cookies.","Warning");return"";}
localStorage.removeItem(cname);}}
function getCookie2(cname)
{try{var name=cname+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++)
{var c=ca[i].trim();if(c.indexOf(name)==0)return c.substring(name.length,c.length);}
return"";}
catch(e){alert("Your browser doesn't accept cookies. Failed to read user preferences and bookmarks. See Help/Troubleshooting/Losing Your Saved Preferences for help on how to set your browser to accept cookies.","Warning");return"";}}
function deleteCookie2(name){document.cookie=name+'=; expires=Thu, 01 Jan 1970 00:00:01 GMT;';}
function setCookie2(cname,cvalue){try{if(getCookie2(cname)!="")deleteCookie2(cname);var exdate=new Date();exdate.setDate(exdate.getDate()+20*365);cvalue=cvalue+"; expires="+exdate.toUTCString();document.cookie=cname+"="+cvalue;}
catch(e){alert("Saving user preferences and bookmarks requires non-private browser mode. Please set this mode and try again. Also, this may be caused by your browser not accepting cookies. See Help/Troubleshooting/Losing Your Saved Preferences for help on how to set your browser to accept cookies.","Warning");}}
function addLabel(point,label,graphicsLayer,fontsize){require(["esri/graphic","esri/symbols/Font","esri/symbols/TextSymbol","dojo/_base/array","dojo/_base/Color"],function(Graphic,Font,TextSymbol,arrayUtils,Color){label=label.replace("/n"," ");var yellow=new Color([255,255,153,1.0]);var font=new Font(fontsize,Font.STYLE_NORMAL,Font.VARIANT_NORMAL,Font.WEIGHT_BOLDER,"Helvetica");var text=new TextSymbol(label,font,new Color("black"));text.setOffset(0,-23);var highlight1=new TextSymbol(label,font,yellow);highlight1.setOffset(1,-25);var highlight2=new TextSymbol(label,font,yellow);highlight2.setOffset(0,-24);var highlight3=new TextSymbol(label,font,yellow);highlight3.setOffset(0,-22);var highlight4=new TextSymbol(label,font,yellow);highlight4.setOffset(-1,-21);var highlight5=new TextSymbol(label,font,yellow);highlight5.setOffset(2,-23);var highlight6=new TextSymbol(label,font,yellow);highlight6.setOffset(-2,-23);graphicsLayer.add(new Graphic(point.geometry,highlight1));graphicsLayer.add(new Graphic(point.geometry,highlight2));graphicsLayer.add(new Graphic(point.geometry,highlight3));graphicsLayer.add(new Graphic(point.geometry,highlight4));graphicsLayer.add(new Graphic(point.geometry,highlight5));graphicsLayer.add(new Graphic(point.geometry,highlight6));graphicsLayer.add(new Graphic(point.geometry,text));map.addLayer(graphicsLayer);graphicsLayer.refresh();});}
function sortArrayOfObj(item){return function(a,b){if(isNaN(a[item])&&a[item]&&a[item].substr(0,4)=="GMU ")
return parseInt(a[item].substring(4))-parseInt(b[item].substring(4));else if(!isNaN(a[item]))
return a[item]-b[item];return(a[item]<b[item])?-1:(a[item]>b[item])?1:0;}}
function sortMultipleArryOfObj(){var props=arguments;if(arguments[0].constructor===Array)props=arguments[0];return function(obj1,obj2){var i=0,result=0,numberOfProperties=props.length;while(result===0&&i<numberOfProperties){result=sortArrayOfObj(props[i])(obj1,obj2);i++;}
return result;}}
Array.prototype.moveUp=function(value,by){var index=this.indexOf(value),newPos=index-(by||1);if(index===-1)
throw new Error("Element not found in array");if(newPos<0)
newPos=0;this.splice(index,1);this.splice(newPos,0,value);};Array.prototype.moveTo=function(value,newPos){var index=this.indexOf(value);if(index===-1)
throw new Error("Element not found in array");if(newPos<0)
newPos=0;this.splice(index,1);this.splice(newPos,0,value);};function detectmob(){if(navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)){return true;}
else{return false;}}
function getScreenClick(evtObj){var clickX=40,clickY=45;if(evtObj.geometry)return evtObj.geometry;else if(evtObj.pageX||evtObj.pageY){clickX=evtObj.pageX;clickY=evtObj.pageY;}
else if((evtObj.clientX||evtObj.clientY)&&document.body&&document.body.scrollLeft!=null){clickX=evtObj.clientX+document.body.scrollLeft;clickY=evtObj.clientY+document.body.scrollTop;}
else if((evtObj.clientX||evtObj.clientY)&&document.compatMode=='CSS1Compat'&&document.documentElement&&document.documentElement.scrollLeft!=null){clickX=evtObj.clientX+document.documentElement.scrollLeft;clickY=evtObj.clientY+document.documentElement.scrollTop;}
else{alert("Did not register tap.","");}
var geometry;require(["esri/geometry/screenUtils","esri/geometry/ScreenPoint"],function(screenUtils,ScreenPoint){var scrGeom=new ScreenPoint(clickX,clickY-44);geometry=new screenUtils.toMapPoint(map.extent,document.getElementById("mapDiv").clientWidth,document.getElementById("mapDiv").clientHeight,scrGeom);scrGeom=null;});return geometry;}